#!/bin/bash

root_check(){
if (( $EUID != 0 )); then
  echo -e "Must be run as root. Type in 'sudo $0' to run it as root."
  exit 1
fi
}

separator(){
sep=
echo $sep
}

configure_interfaces(){
cat >> /etc/dhcpcd.conf << EOL

denyinterfaces enp1s0
EOL

cat > /etc/network/interfaces << EOL
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

#iface enp3s0 inet manual

allow-hotplug enp1s0
iface enp1s0 inet static
    address 172.24.1.1
    netmask 255.255.255.0
    network 172.24.1.0
    broadcast 172.24.1.255
#    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

EOL
}

configure_dnsmasq(){

dnsmasq_conf=/etc/dnsmasq.conf
dnsmasq_conf_bak=/etc/dnsmasq.conf.org.bak

if [ -f $dnsmasq_conf ];
then
	cp -f $dnsmasq_conf $dnsmasq_conf_bak
fi

cat > $dnsmasq_conf << EOL
interface=enp1s0      						# Use interface enp1s0
listen-address=172.24.1.1 					# Explicitly specify the address to listen on
bind-interfaces      						# Bind to the interface to make sure we aren't sending things elsewhere
server=1.1.1.1       						# Forward DNS requests to Google DNS
domain-needed        						# Don't forward short names
bogus-priv           						# Never forward addresses in the non-routed address spaces
dhcp-range=172.24.1.50,172.24.1.150,12h 	# Assign IP addresses between 172.24.1.50 and 172.24.1.150 with a 12 hour lease time
EOL
}

configure_ipv4(){

sysctl_conf=/etc/sysctl.conf
sysctl_conf_bak=/etc/sysctl.conf.org.bak

if [ -f $sysctl_conf ];
then
	echo "Found existing: $sysctl_conf"
	echo "Backup location: $sysctl_conf_bak"
	cp -f $sysctl_conf $sysctl_conf_bak
	echo ""
fi

sed -i "s/#net.ipv4.ip_forward/net.ipv4.ip_forward/g" $sysctl_conf

sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

ipv4nat_conf="/etc/iptables.ipv4.nat"
ipv4nat_conf_bak="/etc/iptables.ipv4.nat.org.bak"

if [ -f $ipv4nat_conf ];
then
	echo "Found existing: $ipv4nat_conf"
	echo "Backup location: $ipv4nat_conf_bak"
	cp -f $ipv4nat_conf $ipv4nat_conf_bak
fi

eval "iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE"
eval "iptables -A FORWARD -i enp3s0 -o enp1s0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
eval "iptables -A FORWARD -i enp1s0 -o enp3s0 -j ACCEPT"

sh -c "iptables-save > /etc/iptables.ipv4.nat"

sed -i 's/^exit 0/iptables-restore < \/etc\/iptables.ipv4.nat\n  \n&/' /etc/rc.local
}

dhcpd_config_update(){
dhcpcd_nat=/lib/dhcpcd/dhcpcd-hooks/70-ipv4-nat
echo "iptables-restore < /etc/iptables.ipv4.nat" > $dhcpcd_nat
}

tor_conf(){

rm /etc/tor/torrc
cat >> /etc/tor/torrc << EOL
Log notice file /var/log/tor/notices.log
VirtualAddrNetwork 10.192.0.0/10
AutomapHostsSuffixes .onion,.exit
AutomapHostsOnResolve 1
TransPort 9040
TransListenAddress 172.24.1.1
DNSPort 53
DNSListenAddress 172.24.1.1

#Exclude Nodes of all of these countries, replace "xx" by country codes, seperate by column.
#ExcludeNodes {xx},{xx}
#ExcludeExitNodes {xx},{xx}

#Havng your exit node to end in a specific country.
#ExitNodes {us} StrictNodes 1
EOL
}

tor_net(){

eval "iptables -F"
eval "iptables -t nat -F"
eval "iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE"
eval "iptables -A FORWARD -i enp3s0 -o enp1s0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
eval "iptables -A FORWARD -i enp1s0 -o enp3s0 -j ACCEPT"
eval "iptables -t nat -A PREROUTING -i enp1s0 -p tcp --dport 22 -j REDIRECT --to-ports 22"
eval "iptables -t nat -A PREROUTING -i enp1s0 -p udp --dport 53 -j REDIRECT --to-ports 53"
eval "iptables -t nat -A PREROUTING -i enp1s0 -p tcp --syn -j REDIRECT --to-ports 9040"
}

tor_start(){
service tor stop
service tor start
}

restart_services(){
service dhcpcd restart
ifdown enp1s0; ifup enp1s0
/etc/init.d/dnsmasq restart
}

start_hotspot(){
service dnsmasq start
}

# param/option check
if [ -z "$1" ];
then
	root_check
	echo "[WORKING..]"
	root_check
	configure_interfaces
	configure_dnsmasq
	tor_conf
	tor_net
	restart_services
	tor_start
	echo "[CONNECTED!]"
	exit 1
elif [[ $1 =~ "start" ]];
then
	start_hotspot
	#exit 1
elif [[ $1 =~ "stop" ]];
then
	stop_hotspot
	exit 1
fi
